### ISSUE TITLE
Pretrained model weights

### ISSUE THREAD

**Issue by Oguzhanercan** [yuangan/VidFace#1]
Hi, can you share the weights, there is no link at readme.

**Comment by yuangan** [comment]
Hi, you can access the files via our [Baidu Disk](https://pan.baidu.com/s/1tzXhLgySyH27w58Jr3xU3g#list/path=%2FVidFace%2Fmodel). If you run into any issues, just let us know.

**Comment by Oguzhanercan** [comment]
@yuangan  Sorry for late reply, I cannot access baidu from Turkiye, can you share with google drive or onedrive?

**Comment by yuangan** [comment]
Hi, our Google Drive link has failed to access. Can you download it from Yandex? Here is a shared link to our [pretrained model](https://disk.yandex.com/d/S926_P6QW_vs4w). However, the dataset is much larger. We are working on uploading them to Yandex drive.

**Comment by Oguzhanercan** [comment]
Yes yandex is accessible, thanks a lot.

**Comment by yuangan** [comment]
We have uploaded all data to [Yandex](https://disk.yandex.com/d/rX2idybrWxv2iQ). Thank you for your attention. Have fun~
